server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    customer-by-address:
      path: /user-by-address/**
      url: http://192.168.99.100:9098
    customer-by-service:
      path: /user-by-service/**
      serviceId: USER-SERVICE
    static:
      path: /static/**

spring:
  application:
    name: zuul-server